gcc45:
  compile:
    - g++
    - -Wall
    - -c
    - -o
    - $output
    - $input
  link:
    - g++
    - -Wall
    - -o
    - $output
    - $input
gcc45-c++11:
  compile:
    - g++
    - -Wall
    - -std=c++0x
    - -c
    - -o
    - $output
    - $input
  link:
    - g++
    - -Wall
    - -std=c++0x
    - -o
    - $output
    - $input
