GLOBAL:
    bucket: cpp-compiler-farm-test
cygwin:
  GLOBAL:
# 48MiB
    memlimit-compile: 50331648
    memlimit-link: 50331648
# 6MiB
    memlimit-execute: 6291456
# 2sec
    cpulimit-compile: 20000000
    cpulimit-link: 20000000
    cpulimit-execute: 20000000
# 120sec
    rtlimit-compile: 120
    rtlimit-link: 120
# 4sec
    rtlimit-execute: 4
    sandbox: win
    sandbox-path: ../sandbox/win/sandbox-compiler.exe
  'vc 8':
    name: '2005 / VC8 / 14.00.50727.42'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 8'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 8\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        FrameworkSDKDir: 'C:\Program Files (x86)\Microsoft Visual Studio 8\SDK\v2.0'
      - DevEnvDir: '%VSINSTALLDIR%\Common7\IDE'
        PATH: '%VSINSTALLDIR%\Common7\IDE;%VCINSTALLDIR%\BIN;%VSINSTALLDIR%\Common7\Tools;%FrameworkSdkDir%\bin;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\VCPackages;%PATH%'
        INCLUDE: '%VCINSTALLDIR%\INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%\LIB;%FrameworkSDKDir%\v2.0\lib;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%\%FrameworkVersion%'
    sandbox-prearg:
      - '..\sandbox\win\vc8\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc8\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - '/Ic:\boost'
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  'vc 9':
    name: '2008 / VC9 / 15.00.30729.01'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        DevEnvDir: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE'
      - PATH: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\VCPackages;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: 'C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\LIB;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc9\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc9\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - '/Ic:\boost'
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  vc10:
    name: '2010 / VC10 / 16.00.30319.01'
    c++11: true
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\'
        FrameworkDir32: 'C:\Windows\Microsoft.NET\Framework\'
        FrameworkVersion32: 'v4.0.30319'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\'
      - DevEnvDir: '%VSINSTALLDIR%Common7\IDE\'
        VS100COMNTOOLS: '%VSINSTALLDIR%Common7\Tools\'
        FrameworkDir: %FrameworkDir32%
        FrameworkVersion: %FrameworkVersion32%
      - PATH: '%FrameworkDir%%Framework35Version%;%FrameworkDir%%FrameworkVersion%;%VSINSTALLDIR%Common7\Tools;%VCINSTALLDIR%BIN;%DevEnvDir%;%WindowsSdkDir%bin\NETFX 4.0 Tools;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: '%VCINSTALLDIR%INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%%FrameworkVersion%;%FrameworkDir%%Framework35Version%;%VCINSTALLDIR%LIB;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc10\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc10\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - '/Ic:\boost'
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  vc11:
    name: '2012 / VC11 / 17.00.50727.1'
    c++11: true
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\'
        FrameworkDir32: 'C:\Windows\Microsoft.NET\Framework\'
        FrameworkVersion32: 'v4.0.30319'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files (x86)\Windows Kits\8.0\'
        WindowsSdkDir_old: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A\'
      - DevEnvDir: '%VSINSTALLDIR%Common7\IDE\'
        VS110COMNTOOLS: '%VSINSTALLDIR%Common7\Tools\'
        FrameworkDir: %FrameworkDir32%
        FrameworkVersion: %FrameworkVersion32%
      - PATH: '%DevEnvDir%;%VCINSTALLDIR%BIN;%VSINSTALLDIR%Common7\Tools;%FrameworkDir%%FrameworkVersion%;%FrameworkDir%%Framework35Version%;%VCINSTALLDIR%VCPackages;%WindowsSdkDir%bin\x86;%WindowsSdkDir_old%bin\NETFX 4.0 Tools;%PATH%'
        INCLUDE: '%VCINSTALLDIR%INCLUDE;%WindowsSdkDir%include\shared;%WindowsSdkDir%include\um;%WindowsSdkDir%include\winrt;%INCLUDE%'
        LIB: '%VCINSTALLDIR%LIB;%WindowsSdkDir%lib\win8\um\x86;%LIB%'
        LIBPATH: '%FrameworkDir%%FrameworkVersion%;%FrameworkDir%%Framework35Version%;%WindowsSdkDir%References\CommonConfiguration\Neutral;%ExtensionSDKDir%\Microsoft.VCLibs\11.0\References\CommonConfiguration\neutral;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc11\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc11\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - '/Ic:\boost'
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
cygwin-test:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: none
  gcc45:
    name: 'gcc 4.5.3'
    compile:
      - g++
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++
      - -Wall
      - -o
      - $output
      - $input
  gcc45-c++11:
    name: 'gcc 4.5.3 with -std=c++0x'
    c++11: true
    compile:
      - g++
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
cygwin-win:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: win
    sandbox-path: ../sandbox/win/sandbox-compiler.exe
  'vc 8':
    name: '2005 / VC8 / 14.00.50727.42'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8'
        VCINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        FrameworkSDKDir: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8\SDK\v2.0'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        DevEnvDir: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8\Common7\IDE'
      - PATH: '%VSINSTALLDIR%\Common7\IDE;%VCINSTALLDIR%\BIN;%VSINSTALLDIR%\Common7\Tools;%VSINSTALLDIR%\SDK\v2.0\bin;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\VCPackages;%PATH%'
        INCLUDE: '%VCINSTALLDIR%\INCLUDE;%WindowsSdkDir%include;C:\Program Files (x86)\Library\boost\boost_1_50;%INCLUDE%'
        LIB: '%VCINSTALLDIR%\LIB;%FrameworkSDKDir%\v2.0\lib;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%\%FrameworkVersion%'
    sandbox-prearg:
      - '..\sandbox\win\vc8\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc8\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  'vc 9':
    name: '2008 / VC9 / 15.00.30729.01'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 9.0'
        VCINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 9.0\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        DevEnvDir: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE'
      - PATH: '%VSINSTALLDIR%\Common7\IDE;%VCINSTALLDIR%\BIN;%VSINSTALLDIR%\Common7\Tools;%FrameworkDir%\%Framework35Version%;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\VCPackages;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: '%VCINSTALLDIR%\INCLUDE;%WindowsSdkDir%include;C:\Program Files (x86)\Library\boost\boost_1_50;%INCLUDE%'
        LIB: '%VCINSTALLDIR%\LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%\%Framework35Version%;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\LIB;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc9\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc9\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  vc10:
    name: '2010 / VC10 / 16.00.40219.01'
    c++11: true
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 10.0\'
        VCINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 10.0\VC\'
        FrameworkDir32: 'C:\Windows\Microsoft.NET\Framework\'
        FrameworkVersion32: 'v4.0.30319'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\'
      - DevEnvDir: '%VSINSTALLDIR%Common7\IDE\'
        VS100COMNTOOLS: '%VSINSTALLDIR%\Common7\Tools\'
        FrameworkDir: %FrameworkDir32%
        FrameworkVersion: %FrameworkVersion32%
      - PATH: '%FrameworkDir%%Framework35Version%;%FrameworkDir%%FrameworkVersion%;%VSINSTALLDIR%Common7\Tools;%VCINSTALLDIR%BIN;%DevEnvDir%;%WindowsSdkDir%bin\NETFX 4.0 Tools;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: '%VCINSTALLDIR%INCLUDE;%WindowsSdkDir%include;C:\Program Files (x86)\Library\boost\boost_1_50;%INCLUDE%'
        LIB: '%VCINSTALLDIR%LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%%FrameworkVersion%;%FrameworkDir%%Framework35Version%;%VCINSTALLDIR%LIB;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc10\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc10\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
linux:
  GLOBAL:
# 72MiB
    memlimit-compile: 75497472
# 48MiB
    memlimit-link: 50331648
# 6MiB
    memlimit-execute: 6291456
# 2sec
    cpulimit-compile: 2
    cpulimit-link: 2
    cpulimit-execute: 2
# 20sec
    rtlimit-compile: 20
# 10sec
    rtlimit-link: 10
# 4sec
    rtlimit-execute: 4
    sandbox: linux
    sandbox-path: ../sandbox/linux/sandbox-compiler
    sandbox-arg:
      - ../sandbox/linux/libsandbox.a
      - -lrt
  gcc44:
    name: 'Ubuntu/Linaro 4.4.7-1ubuntu2'
    compile:
      - g++-4.4
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.4
      - -Wall
      - -o
      - $output
      - $input
  gcc44-c++11:
    name: 'Ubuntu/Linaro 4.4.7-1ubuntu2'
    c++11: true
    compile:
      - g++-4.4
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.4
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc45:
    name: 'Ubuntu/Linaro 4.5.3-12ubuntu2'
    compile:
      - g++-4.5
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.5
      - -Wall
      - -o
      - $output
      - $input
  gcc45-c++11:
    name: 'Ubuntu/Linaro 4.5.3-12ubuntu2'
    c++11: true
    compile:
      - g++-4.5
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.5
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc46:
    name: 'Ubuntu/Linaro 4.6.3-1ubuntu5'
    compile:
      - g++-4.6
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.6
      - -Wall
      - -o
      - $output
      - $input
  gcc46-c++11:
    name: 'Ubuntu/Linaro 4.6.3-1ubuntu5'
    c++11: true
    compile:
      - g++-4.6
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.6
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc47:
    name: 'Ubuntu/Linaro 4.7.2-11precise2'
    compile:
      - g++-4.7
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.7
      - -Wall
      - -o
      - $output
      - $input
  gcc47-c++11:
    name: 'Ubuntu/Linaro 4.7.2-11precise2'
    c++11: true
    compile:
      - g++-4.7
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.7
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc48:
    name: 'gcc 4.8.0 20130210 (exp.)'
    compile:
      - g++-4.8
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.8
      - -Wall
      - -o
      - $output
      - $input
  gcc48-c++11:
    name: 'gcc 4.8.0 20130210 (exp.)'
    c++11: true
    compile:
      - g++-4.8
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.8
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  clang30:
    name: 'Ubuntu clang 3.0-6ubuntu3'
# 48MiB
    memlimit-link: 50331648
    compile:
      - clang++
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++
      - -Wall
      - -o
      - $output
      - $input
  clang30-c++11:
    name: 'Ubuntu clang 3.0-6ubuntu3'
    c++11: true
# 48MiB
    memlimit-link: 50331648
    compile:
      - clang++
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++
      - -Wall
      - -o
      - $output
      - $input
  clang31:
    name: 'Ubuntu clang 3.1-debian8ppa2'
# 48MiB
    memlimit-link: 50331648
    compile:
      - clang++-3.1
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++-3.1
      - -Wall
      - -o
      - $output
      - $input
  clang31-c++11:
    name: 'Ubuntu clang 3.1-debian8ppa2'
    c++11: true
# 48MiB
    memlimit-link: 50331648
    compile:
      - clang++-3.1
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++-3.1
      - -Wall
      - -o
      - $output
      - $input
  clang32:
    name: 'Ubuntu clang 3.2-debian1ppa1~exp5'
# 48MiB
    memlimit-link: 50331648
    compile:
      - clang++-3.2
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++-3.2
      - -Wall
      - -o
      - $output
      - $input
  clang32-c++11:
    name: 'Ubuntu clang 3.2-debian1ppa1~exp5'
    c++11: true
# 48MiB
    memlimit-link: 50331648
    compile:
      - clang++-3.2
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++-3.2
      - -Wall
      - -o
      - $output
      - $input
