cygwin:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: none
  gcc45:
    name: 'gcc 4.5.3'
    compile:
      - g++
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++
      - -Wall
      - -o
      - $output
      - $input
  gcc45-c++11:
    name: 'gcc 4.5.3 with -std=c++0x'
    compile:
      - g++
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
linux:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: none
  gcc44:
    name: 'gcc 4.4.7'
    compile:
      - g++-4.4
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.4
      - -Wall
      - -o
      - $output
      - $input
  gcc44-c++11:
    name: 'gcc 4.4.7 with -std=c++0x'
    compile:
      - g++-4.4
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.4
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc45:
    name: 'gcc 4.5.3'
    compile:
      - g++-4.5
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.5
      - -Wall
      - -o
      - $output
      - $input
  gcc45-c++11:
    name: 'gcc 4.5.3 with -std=c++0x'
    compile:
      - g++-4.5
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.5
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc46:
    name: 'gcc 4.6.3'
    compile:
      - g++-4.6
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.6
      - -Wall
      - -o
      - $output
      - $input
  gcc46-c++11:
    name: 'gcc 4.6.3 with -std=c++0x'
    compile:
      - g++-4.6
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.6
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc47:
    name: 'gcc 4.7.1'
    compile:
      - g++-4.7
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.7
      - -Wall
      - -o
      - $output
      - $input
  gcc47-c++11:
    name: 'gcc 4.7.1 with -std=c++0x'
    compile:
      - g++-4.7
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.7
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc48:
    name: 'gcc 4.8.0 20120801 (exp.)'
    compile:
      - g++-4.8
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.8
      - -Wall
      - -o
      - $output
      - $input
  gcc48-c++11:
    name: 'gcc 4.8.0 20120801 (exp.) with -std=c++0x'
    compile:
      - g++-4.8
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.8
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  clang30:
    name: 'Ubuntu clang 3.0-6ubuntu3'
    compile:
      - clang++
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++
      - -Wall
      - -o
      - $output
      - $input
  clang30-c++11:
    name: 'Ubuntu clang 3.0-6ubuntu3'
    compile:
      - clang++
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
