cygwin:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: win
  'vc 8':
    name: '2005 / VC8 / 14.00.50727.42'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 8'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 8\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        FrameworkSDKDir: 'C:\Program Files (x86)\Microsoft Visual Studio 8\SDK\v2.0'
      - DevEnvDir: '%VSINSTALLDIR%\Common7\IDE'
        PATH: '%VSINSTALLDIR%\Common7\IDE;%VCINSTALLDIR%\BIN;%VSINSTALLDIR%\Common7\Tools;%FrameworkSdkDir%\bin;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\VCPackages;%PATH%'
        INCLUDE: '%VCINSTALLDIR%\INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%\LIB;%FrameworkSDKDir%\v2.0\lib;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%\%FrameworkVersion%'
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /Fe$output
      - $input
  'vc 9':
    name: '2008 / VC9 / 15.00.30729.01'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        DevEnvDir: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE'
      - PATH: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\VCPackages;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: 'C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\LIB;%LIBPATH%'
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /Fe$output
      - $input
  vc10:
    name: '2010 / VC10 / 16.00.30319.01'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\'
        VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\'
        FrameworkDir32: 'C:\Windows\Microsoft.NET\Framework\'
        FrameworkVersion32: 'v4.0.30319'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\'
      - DevEnvDir: '%VSINSTALLDIR%Common7\IDE\'
        VS100COMNTOOLS: '%VSINSTALLDIR%Common7\Tools\'
        FrameworkDir: %FrameworkDir32%
        FrameworkVersion: %FrameworkVersion32%
      - PATH: '%FrameworkDir%%Framework35Version%;%FrameworkDir%%FrameworkVersion%;%VSINSTALLDIR%Common7\Tools;%VCINSTALLDIR%BIN;%DevEnvDir%;%WindowsSdkDir%bin\NETFX 4.0 Tools;%WindowsSdkDir%bin;'
        INCLUDE: '%VCINSTALLDIR%INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%%FrameworkVersion%;%FrameworkDir%%Framework35Version%;%VCINSTALLDIR%LIB;%LIBPATH%'
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /Fe$output
      - $input
cygwin-test:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: none
  gcc45:
    name: 'gcc 4.5.3'
    compile:
      - g++
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++
      - -Wall
      - -o
      - $output
      - $input
  gcc45-c++11:
    name: 'gcc 4.5.3 with -std=c++0x'
    compile:
      - g++
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
cygwin-win:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: win
    sandbox-path: ../sandbox/win/sandbox-compiler.exe
  'vc 8':
    name: '2005 / VC8 / 14.00.50727.42'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8'
        VCINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        FrameworkSDKDir: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8\SDK\v2.0'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        DevEnvDir: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 8\Common7\IDE'
      - PATH: '%VSINSTALLDIR%\Common7\IDE;%VCINSTALLDIR%\BIN;%VSINSTALLDIR%\Common7\Tools;%VSINSTALLDIR%\SDK\v2.0\bin;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\VCPackages;%PATH%'
        INCLUDE: '%VCINSTALLDIR%\INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%\LIB;%FrameworkSDKDir%\v2.0\lib;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%\%FrameworkVersion%'
    sandbox-prearg:
      - '..\sandbox\win\vc8\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc8\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  'vc 9':
    name: '2008 / VC9 / 15.00.30729.01'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 9.0'
        VCINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 9.0\VC'
        FrameworkDir: 'C:\Windows\Microsoft.NET\Framework'
        FrameworkVersion: 'v2.0.50727'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\'
        DevEnvDir: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE'
      - PATH: '%VSINSTALLDIR%\Common7\IDE;%VCINSTALLDIR%\BIN;%VSINSTALLDIR%\Common7\Tools;%FrameworkDir%\%Framework35Version%;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\VCPackages;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: '%VCINSTALLDIR%\INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%\LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%\%Framework35Version%;%FrameworkDir%\%FrameworkVersion%;%VCINSTALLDIR%\LIB;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc9\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc9\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
  vc10:
    name: '2010 / VC10 / 16.00.40219.01'
    cygwin2native: true
    env:
      - VSINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 10.0\'
        VCINSTALLDIR: 'C:\Program Files (x86)\Application\Microsoft Visual Studio 10.0\VC\'
        FrameworkDir32: 'C:\Windows\Microsoft.NET\Framework\'
        FrameworkVersion32: 'v4.0.30319'
        Framework35Version: 'v3.5'
        WindowsSdkDir: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\'
      - DevEnvDir: '%VSINSTALLDIR%Common7\IDE\'
        VS100COMNTOOLS: '%VSINSTALLDIR%\Common7\Tools\'
        FrameworkDir: %FrameworkDir32%
        FrameworkVersion: %FrameworkVersion32%
      - PATH: '%FrameworkDir%%Framework35Version%;%FrameworkDir%%FrameworkVersion%;%VSINSTALLDIR%Common7\Tools;%VCINSTALLDIR%BIN;%DevEnvDir%;%WindowsSdkDir%bin\NETFX 4.0 Tools;%WindowsSdkDir%bin;%PATH%'
        INCLUDE: '%VCINSTALLDIR%INCLUDE;%WindowsSdkDir%include;%INCLUDE%'
        LIB: '%VCINSTALLDIR%LIB;%WindowsSdkDir%lib;%LIB%'
        LIBPATH: '%FrameworkDir%%FrameworkVersion%;%FrameworkDir%%Framework35Version%;%VCINSTALLDIR%LIB;%LIBPATH%'
    sandbox-prearg:
      - '..\sandbox\win\vc10\sandbox.obj'
    sandbox-arg:
      - '..\sandbox\win\vc10\sandbox-win-standalone.lib'
      - advapi32.lib
      - user32.lib
      - shell32.lib
      - dbghelp.lib
      - psapi.lib
    compile:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /c
      - /Fo$output
      - $input
    link:
      - cl
      - /nologo
      - /W3
      - /EHsc
      - /MDd
      - /Fe$output
      - $input
linux:
  GLOBAL:
    memlimit-compile: 0
    memlimit-execute: 0
    cpulimit-compile: 0
    cpulimit-execute: 0
    sandbox: none
  gcc44:
    name: 'gcc 4.4.7'
    compile:
      - g++-4.4
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.4
      - -Wall
      - -o
      - $output
      - $input
  gcc44-c++11:
    name: 'gcc 4.4.7 with -std=c++0x'
    compile:
      - g++-4.4
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.4
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc45:
    name: 'gcc 4.5.3'
    compile:
      - g++-4.5
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.5
      - -Wall
      - -o
      - $output
      - $input
  gcc45-c++11:
    name: 'gcc 4.5.3 with -std=c++0x'
    compile:
      - g++-4.5
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.5
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc46:
    name: 'gcc 4.6.3'
    compile:
      - g++-4.6
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.6
      - -Wall
      - -o
      - $output
      - $input
  gcc46-c++11:
    name: 'gcc 4.6.3 with -std=c++0x'
    compile:
      - g++-4.6
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.6
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc47:
    name: 'gcc 4.7.1'
    compile:
      - g++-4.7
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.7
      - -Wall
      - -o
      - $output
      - $input
  gcc47-c++11:
    name: 'gcc 4.7.1 with -std=c++0x'
    compile:
      - g++-4.7
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.7
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  gcc48:
    name: 'gcc 4.8.0 20120801 (exp.)'
    compile:
      - g++-4.8
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.8
      - -Wall
      - -o
      - $output
      - $input
  gcc48-c++11:
    name: 'gcc 4.8.0 20120801 (exp.) with -std=c++0x'
    compile:
      - g++-4.8
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - g++-4.8
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
  clang30:
    name: 'Ubuntu clang 3.0-6ubuntu3'
    compile:
      - clang++
      - -Wall
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++
      - -Wall
      - -o
      - $output
      - $input
  clang30-c++11:
    name: 'Ubuntu clang 3.0-6ubuntu3'
    compile:
      - clang++
      - -Wall
      - -std=c++0x
      - -c
      - -o
      - $output
      - $input
    link:
      - clang++
      - -Wall
      - -std=c++0x
      - -o
      - $output
      - $input
